import type { ProfessorReviewPublicRow } from "@/lib/professor-reviews/types";
import type { CalendarEvent, Course } from "@/lib/types";

// Real schedule data from 2026-05-04 week (Mon-Sat)
// Extracted from horario-2026-05-10.ics
const weekStart = new Date(2026, 4, 4); // Monday May 4, 2026

function eventDate(weekday: number, time: string): Date {
  const dayOffset = weekday === 0 ? 6 : weekday - 1;
  const d = new Date(weekStart);
  d.setDate(d.getDate() + dayOffset);
  const [hours, minutes] = time.split(":").map(Number);
  d.setHours(hours, minutes, 0, 0);
  return d;
}

export const demoCalendarEvents: CalendarEvent[] = [
  {
    id: "MA1403-02-20260505T093000",
    title: "MATEMÁTICA DISCRETA",
    courseName: "MATEMÁTICA DISCRETA",
    courseCode: "MA1403",
    groupCode: "02",
    groupId: "MA1403-02",
    groupType: "REGULAR",
    professors: ["CHAVARRIA MOLINA JEFFRY"],
    classroom: "D3-11",
    campusName: "CAMPUS TECNOLOGICO CENTRAL CARTAGO",
    color: "violet",
    start: eventDate(2, "09:30"),
    end: eventDate(2, "11:20"),
    courseId: "MA1403",
    group: 2,
  },
  {
    id: "IC1802-05-20260506T073000",
    title: "INTRODUCCIÓN A LA PROGRAMACIÓN",
    courseName: "INTRODUCCIÓN A LA PROGRAMACIÓN",
    courseCode: "IC1802",
    groupCode: "05",
    groupId: "IC1802-05",
    groupType: "SEMIPRESENCIAL",
    professors: ["MATA RODRIGUEZ WILLIAM"],
    classroom: "B6-02",
    campusName: "CAMPUS TECNOLOGICO CENTRAL CARTAGO",
    color: "orange",
    start: eventDate(3, "07:30"),
    end: eventDate(3, "09:20"),
    courseId: "IC1802",
    group: 5,
  },
  {
    id: "IC1803-05-20260506T093000",
    title: "TALLER DE PROGRAMACIÓN",
    courseName: "TALLER DE PROGRAMACIÓN",
    courseCode: "IC1803",
    groupCode: "05",
    groupId: "IC1803-05",
    groupType: "SEMIPRESENCIAL",
    professors: ["MATA RODRIGUEZ WILLIAM"],
    classroom: "B6-05",
    campusName: "CAMPUS TECNOLOGICO CENTRAL CARTAGO",
    color: "fuchsia",
    start: eventDate(3, "09:30"),
    end: eventDate(3, "11:20"),
    courseId: "IC1803",
    group: 5,
  },
  {
    id: "CI1106-23-20260507T130000",
    title: "COMUNICACIÓN ESCRITA",
    courseName: "COMUNICACIÓN ESCRITA",
    courseCode: "CI1106",
    groupCode: "23",
    groupId: "CI1106-23",
    groupType: "VIRTUAL",
    professors: ["ROMERO ALVAREZ ERICKA"],
    classroom: null,
    campusName: "CAMPUS TECNOLOGICO CENTRAL CARTAGO",
    color: "yellow",
    start: eventDate(4, "13:00"),
    end: eventDate(4, "15:50"),
    courseId: "CI1106",
    group: 23,
  },
  {
    id: "MA1403-02-20260507T093000",
    title: "MATEMÁTICA DISCRETA",
    courseName: "MATEMÁTICA DISCRETA",
    courseCode: "MA1403",
    groupCode: "02",
    groupId: "MA1403-02",
    groupType: "REGULAR",
    professors: ["CHAVARRIA MOLINA JEFFRY"],
    classroom: "D3-11",
    campusName: "CAMPUS TECNOLOGICO CENTRAL CARTAGO",
    color: "violet",
    start: eventDate(4, "09:30"),
    end: eventDate(4, "11:20"),
    courseId: "MA1403",
    group: 2,
  },
  {
    id: "IC1802-05-20260508T073000",
    title: "INTRODUCCIÓN A LA PROGRAMACIÓN",
    courseName: "INTRODUCCIÓN A LA PROGRAMACIÓN",
    courseCode: "IC1802",
    groupCode: "05",
    groupId: "IC1802-05",
    groupType: "SEMIPRESENCIAL",
    professors: ["MATA RODRIGUEZ WILLIAM"],
    classroom: "B6-02",
    campusName: "CAMPUS TECNOLOGICO CENTRAL CARTAGO",
    color: "orange",
    start: eventDate(5, "07:30"),
    end: eventDate(5, "09:20"),
    courseId: "IC1802",
    group: 5,
  },
  {
    id: "IC1803-05-20260508T093000",
    title: "TALLER DE PROGRAMACIÓN",
    courseName: "TALLER DE PROGRAMACIÓN",
    courseCode: "IC1803",
    groupCode: "05",
    groupId: "IC1803-05",
    groupType: "SEMIPRESENCIAL",
    professors: ["MATA RODRIGUEZ WILLIAM"],
    classroom: "B6-05",
    campusName: "CAMPUS TECNOLOGICO CENTRAL CARTAGO",
    color: "fuchsia",
    start: eventDate(5, "09:30"),
    end: eventDate(5, "11:20"),
    courseId: "IC1803",
    group: 5,
  },
  {
    id: "CI1230-11-20260508T130000",
    title: "INGLÉS I",
    courseName: "INGLÉS I",
    courseCode: "CI1230",
    groupCode: "11",
    groupId: "CI1230-11",
    groupType: "VIRTUAL",
    professors: ["HERRERA JIMENEZ INGRID"],
    classroom: null,
    campusName: "CAMPUS TECNOLOGICO CENTRAL CARTAGO",
    color: "red",
    start: eventDate(5, "13:00"),
    end: eventDate(5, "15:50"),
    courseId: "CI1230",
    group: 11,
  },
];

// Static curriculum data for course relation graph demo
// Real data from IC4301 - BASES DE DATOS I (plan 48, Ingeniería en Computación 2022)
export const demoRelationCourse: Course = {
  id: "IC4301",
  code: "IC4301",
  name: "BASES DE DATOS I",
  credits: 4,
  hours: 9,
  semester: 3,
  status: "not_taken",
  prerequisites: ["IC2001"],
  corequisites: ["MA1103"],
};

export const demoPrerequisites: Course[] = [
  {
    id: "IC2001",
    code: "IC2001",
    name: "ESTRUCTURAS DE DATOS",
    credits: 4,
    hours: 12,
    semester: 2,
    status: "not_taken",
    prerequisites: ["IC1802", "IC1803"],
    corequisites: [],
  },
];

export const demoCorequisites: Course[] = [
  {
    id: "MA1103",
    code: "MA1103",
    name: "CÁLCULO Y ÁLGEBRA LINEAL",
    credits: 4,
    hours: 4,
    semester: 3,
    status: "not_taken",
    prerequisites: ["MA1102"],
    corequisites: [],
  },
];

export const demoDependents: Course[] = [
  {
    id: "IC4302",
    code: "IC4302",
    name: "BASES DE DATOS II",
    credits: 3,
    hours: 9,
    semester: 4,
    status: "not_taken",
    prerequisites: ["IC4301"],
    corequisites: [],
  },
];

// Static professor review data for landing page demo
export const demoReviewRows: ProfessorReviewPublicRow[] = [
  {
    review_id: 1,
    professor_id: "1178",
    course_id: 1037,
    course_code: "IC1400",
    course_name: "FUNDAMENTOS DE ORGANIZACIÓN DE COMPUTADORAS",
    comment:
      "El profesor explica muy bien los fundamentos de bases de datos relacionales. Los laboratorios son prácticos y ayudan a entender SQL. Eso sí, los exámenes son largos y hay que estudiar bastante.",
    ease_score: 6.5,
    quality_score: 9.0,
    clarity_score: 8.5,
    fairness_score: 8.0,
    attendance_required: false,
    grade_received: "85",
    engagement_level: 4,
    tags: ["Explica con claridad", "Proyecto útil", "Exámenes retadores"],
    status: "approved",
    created_at: "2026-03-15T14:30:00Z",
    like_count: 0,
    dislike_count: 0,
    my_reaction: null,
    total_count: 3,
  },
  {
    review_id: 2,
    professor_id: "1192",
    course_id: 1038,
    course_code: "IC3101",
    course_name: "ARQUITECTURA DE COMPUTADORES",
    comment:
      "Muy buen profesor, siempre dispuesto a ayudar. Las clases son interactivas y el proyecto final integra todo lo visto durante el semestre. Recomiendo llevar el curso con él.",
    ease_score: 7.0,
    quality_score: 9.5,
    clarity_score: 9.0,
    fairness_score: 9.0,
    attendance_required: true,
    grade_received: "92",
    engagement_level: 5,
    tags: ["Da buena retroalimentación", "Brinda apoyo", "Tomaría su clase nuevamente"],
    status: "approved",
    created_at: "2026-04-02T10:15:00Z",
    like_count: 0,
    dislike_count: 0,
    my_reaction: null,
    total_count: 3,
  },
  {
    review_id: 3,
    professor_id: "1171",
    course_id: 1039,
    course_code: "IC4700",
    course_name: "LENGUAJES DE PROGRAMACIÓN",
    comment:
      "Las clases son claras y bien estructuradas. El material de apoyo en el TEC Digital es completo. Los quizzes semanales ayudan a llevar el curso al día. Muy recomendada.",
    ease_score: 8.0,
    quality_score: 8.5,
    clarity_score: 9.5,
    fairness_score: 7.5,
    attendance_required: true,
    grade_received: "78",
    engagement_level: 3,
    tags: ["Explica con claridad", "Da buena retroalimentación"],
    status: "approved",
    created_at: "2026-02-20T08:00:00Z",
    like_count: 0,
    dislike_count: 0,
    my_reaction: null,
    total_count: 3,
  },
];
