-- ============================================================================
-- FIX SEED FOR 20260707T070839Z
-- ============================================================================

BEGIN;
SET LOCAL TIME ZONE 'UTC';

UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 1;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 2;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 4;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 5;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 7;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 8;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 9;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 10;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 11;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 12;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 13;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 14;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 15;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 16;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 17;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 18;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 19;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 20;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 28;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 29;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 30;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 31;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 32;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 33;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 34;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 35;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 36;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 37;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 38;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 39;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 46;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 47;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 48;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 49;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 50;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 51;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 55;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 56;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 57;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 58;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 61;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 62;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 63;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 64;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 65;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 66;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 67;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 68;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 69;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 70;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 71;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 72;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 73;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 74;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 75;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 76;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 77;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 78;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 79;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 80;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 81;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 82;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 83;
UPDATE public.academic_term SET is_active = FALSE, deactivated_at = '2026-04-24T10:06:18.124049+00:00', updated_at = NOW() WHERE id = 84;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 97;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 98;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 99;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 100;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 103;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 104;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 105;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 106;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 107;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 108;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 109;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 110;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 115;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 116;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 118;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 119;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 120;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 121;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 122;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 123;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 124;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 125;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 126;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 127;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 128;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 129;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 130;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 131;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 132;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 133;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 134;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 135;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 136;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 137;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 138;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 139;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 140;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 141;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 142;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 143;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 144;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 145;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 146;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 147;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 148;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 149;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 150;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 151;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 152;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 153;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 154;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 155;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 156;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 157;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 158;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 159;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 160;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 161;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 162;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 163;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 164;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 165;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 166;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 167;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 168;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 169;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 170;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 171;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 172;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 173;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 174;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 175;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 176;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 177;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 178;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 179;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 180;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 181;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 182;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 183;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 184;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 185;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 186;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 187;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 188;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 189;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 190;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 191;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 192;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 193;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 194;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 195;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 196;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 197;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 198;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 199;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 200;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 201;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 202;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 203;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 204;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 205;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 206;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 207;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 208;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 209;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 210;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 211;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 212;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 213;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 214;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 215;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 216;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 217;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 218;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 219;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 220;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 221;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 222;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 223;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 224;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 225;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 226;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 227;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 228;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 229;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 230;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 231;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 232;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 233;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 234;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 235;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 236;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 237;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 238;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 239;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 240;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 241;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 242;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 243;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 244;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 245;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 246;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 247;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 248;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 249;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 250;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 251;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 252;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 253;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 254;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 255;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 256;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 257;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 258;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 259;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 260;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 261;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 262;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 263;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 264;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 265;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 266;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 267;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 268;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 269;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 270;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 271;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 272;
UPDATE public.academic_term SET is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 273;

UPDATE public.course SET name = E'MINERÍA DE DATOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 39;
UPDATE public.course SET name = E'ARQUITECTURA DE INFORMACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 45;
UPDATE public.course SET name = E'PROCESAMIENTO DIGITAL DE IMÁGENES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 50;
UPDATE public.course SET name = E'PRINCIPIOS DE COMPUTACIÓN CUÁNTICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 53;
UPDATE public.course SET name = E'GESTIÓN DE LA SEGURIDAD DE LA INFORMACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 56;
UPDATE public.course SET name = E'VISUALIZACIÓN DE INFORMACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 65;
UPDATE public.course SET name = E'COMPUTACIÓN PARALELA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 69;
UPDATE public.course SET name = E'ESTRATEGIAS DE DESARROLLO DE GOBIERNO DIGITAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 71;
UPDATE public.course SET name = E'DISEÑO MECÁNICO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 106;
UPDATE public.course SET name = E'AIRE ACONDICIONADO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 107;
UPDATE public.course SET name = E'AUTOMATISMO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 110;
UPDATE public.course SET name = E'AHORRO ENERGÉTICO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 113;
UPDATE public.course SET name = E'FINANZAS INTERNACIONALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 219;
UPDATE public.course SET name = E'INVERSIONES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 220;
UPDATE public.course SET name = E'FINANZAS AVANZADAS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 221;
UPDATE public.course SET name = E'FINANZAS ESTRATÉGICAS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 223;
UPDATE public.course SET name = E'PUBLICIDAD Y PROMOCIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 232;
UPDATE public.course SET name = E'MERCADEO ESTRATÉGICO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 235;
UPDATE public.course SET name = E'SEMINARIO DE GRADUACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 258;
UPDATE public.course SET name = E'GERENCIA DE CALIDAD', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 285;
UPDATE public.course SET name = E'GESTIÓN DEL CONOCIMIENTO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 286;
UPDATE public.course SET name = E'EVALUACIÓN MEJORA CONTINUA Y EXCELENCIA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 287;
UPDATE public.course SET name = E'SEGURIDAD DE SOFTWARE AVANZADO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 316;
UPDATE public.course SET name = E'TECNOLOGÍAS PARA EL MEJORAMIENTO DE LA PRIVACIDAD', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 317;
UPDATE public.course SET name = E'SEGURIDAD E INTERNET DE LAS COSAS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 318;
UPDATE public.course SET name = E'SEGURIDAD EN LA NUBE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 319;
UPDATE public.course SET name = E'SEGURIDAD DE REDES AVANZADAS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 320;
UPDATE public.course SET name = E'DEFENSA Y ATAQUE DE SISTEMAS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 321;
UPDATE public.course SET name = E'INGENIERÍA INVERSA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 322;
UPDATE public.course SET name = E'ADMINISTRACIÓN SEGURA DE DATOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 323;
UPDATE public.course SET name = E'RESPUESTA ANTE INCIDENTES, RIESGO Y CONTINUIDAD', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 324;
UPDATE public.course SET name = E'CIBERCRIMEN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 325;
UPDATE public.course SET name = E'COMPUTACIÓN GRAFICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 330;
UPDATE public.course SET name = E'DEEP LEARNING', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 331;
UPDATE public.course SET name = E'REALIDAD VIRTUAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 333;
UPDATE public.course SET name = E'APRENDIZAJE AUTOMÁTICO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 334;
UPDATE public.course SET name = E'PROCESAMIENTO DE LENGUAJE NATURAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 335;
UPDATE public.course SET name = E'OPTIMIZACIÓN Y PROGRAMACIÓN NUMÉRICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 336;
UPDATE public.course SET name = E'ESTRATEGIAS DE GESTIÓN PARA PROYECTOS DE CONSTRUCCIÓN SOSTENIBLES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 375;
UPDATE public.course SET name = E'BIM Y LA GESTIÓN DE PROYECTOS DE CONSTRUCCIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 376;
UPDATE public.course SET name = E'GESTIÓN DE PROYECTOS Y MODELOS AGILES EN DESARROLLO DE SOFTWARE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 386;
UPDATE public.course SET name = E'AUDITORÍA DE PROYECTOS DE TI', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 387;
UPDATE public.course SET name = E'ESTIMACIÓN EN PROYECTOS DE DESARROLLO DE SOFTWARE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 390;
UPDATE public.course SET name = E'GESTIÓN DE PROYECTOS GUBERNAMENTALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 398;
UPDATE public.course SET name = E'AUDITORÍA DE PROYECTOS EN EL SECTOR PÚBLICO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 399;
UPDATE public.course SET name = E'GESTIÓN DE PROGRAMAS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 401;
UPDATE public.course SET name = E'NATACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 492;
UPDATE public.course SET name = E'JUEGOS Y DEPORTES EN CONJUNTO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 493;
UPDATE public.course SET name = E'ACONDICIONAMIENTO FÍSICO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 494;
UPDATE public.course SET name = E'BALONCESTO RECREATIVO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 495;
UPDATE public.course SET name = E'ARTES DRAMÁTICAS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 498;
UPDATE public.course SET name = E'ACCIÓN SOCIAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 499;
UPDATE public.course SET name = E'DANZA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 500;
UPDATE public.course SET name = E'ARTES VISUALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 501;
UPDATE public.course SET name = E'ARTES MUSICALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 502;
UPDATE public.course SET name = E'APRECIACIÓN LITERARIA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 503;
UPDATE public.course SET name = E'APRECIACIÓN DE CINE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 504;
UPDATE public.course SET name = E'DINÁMICA DE LA CULTURA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 506;
UPDATE public.course SET name = E'DANZA MODERNA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 507;
UPDATE public.course SET name = E'EXPRESIÓN CORPORAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 508;
UPDATE public.course SET name = E'APRECIACIÓN MUSICAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 512;
UPDATE public.course SET name = E'TÉCNICA DEL CANTO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 513;
UPDATE public.course SET name = E'ESTRATEGIAS DE ENSEÑANZA Y APRENDIZAJE EN ETFP', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 523;
UPDATE public.course SET name = E'INNOVACIÓN Y TECNOLOGÍA EN ETFP', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 525;
UPDATE public.course SET name = E'ATLETISMO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 574;
UPDATE public.course SET name = E'BÉISBOL-SOFTBOL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 578;
UPDATE public.course SET name = E'AJEDREZ', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 583;
UPDATE public.course SET name = E'BALONCESTO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 584;
UPDATE public.course SET name = E'FUTBOL I', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 585;
UPDATE public.course SET name = E'FUTBOL SALA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 586;
UPDATE public.course SET name = E'VOLEIBOL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 587;
UPDATE public.course SET name = E'AUTO ESTIMA Y PROYECTO DE VIDA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 650;
UPDATE public.course SET name = E'CULTURA POPULAR', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 652;
UPDATE public.course SET name = E'LA TRAGEDIA SHAKESPEARIANA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 653;
UPDATE public.course SET name = E'DESARROLLO SOSTENIBLE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 658;
UPDATE public.course SET name = E'LA REVOLUCIÓN CIENTÍFICA DEL SIGLO XVI Y XVII', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 659;
UPDATE public.course SET name = E'LATINOAMÉRICA Y SU DEPENDENCIA POLÍTICA Y ECONÓMICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 663;
UPDATE public.course SET name = E'EL DESARROLLO DE LA CIENCIA EN COSTA RICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 664;
UPDATE public.course SET name = E'LO IMAGINARIO EN EL ARTE LOS SUEÑOS Y LA LOCURA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 672;
UPDATE public.course SET name = E'SEXUALIDAD PAREJA Y TEORÍA PSICOSEXUAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 673;
UPDATE public.course SET name = E'LA COMEDIA SHAKESPERIANA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 677;
UPDATE public.course SET name = E'CINE Y LITERATURA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 681;
UPDATE public.course SET name = E'INFORMÁTICA Y SOCIEDAD', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 682;
UPDATE public.course SET name = E'GLOBALIZACIÓN Y HUMANISMO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 683;
UPDATE public.course SET name = E'ÉTICA ATEMPORAL: ENSEÑANZAS DEL PASADO PARA VIVIR NUESTRO FUTURO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 687;
UPDATE public.course SET name = E'PARADIGMAS DEL DESARROLLO SOSTENIBLE: CRÍTICA DESDE PERSPECTIVA ILOLIST', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 688;
UPDATE public.course SET name = E'OPORTUNIDADES PROFESIONALES DESDE UNA PERSPECTIVA DE GÉNERO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 689;
UPDATE public.course SET name = E'TEATRO EN COSTA RICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 692;
UPDATE public.course SET name = E'EDUCACIÓN EN NUESTROS TIEMPOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 695;
UPDATE public.course SET name = E'IDENTIDAD Y CULTURA COSTARRICENSE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 698;
UPDATE public.course SET name = E'LA BOMBA ATÓMICA EN HIROSHIMA Y NAGASAKI Y LOS ESFUERZOS DE DESARME', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 699;
UPDATE public.course SET name = E'MASCULINIDAD GÉNEROS Y ASIGNACIONES SOCIALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 700;
UPDATE public.course SET name = E'PATRIMONIO E IDENTIDAD CULTURAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 701;
UPDATE public.course SET name = E'IDENTIDAD Y CULTURA COSTARRICENSE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 709;
UPDATE public.course SET name = E'GÉNERO Y JUVENTUD COMO CONSTRUCCIONES CULTURALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 716;
UPDATE public.course SET name = E'SEXUALIDAD Y PREVENCIÓN DIMENSIÓN SOCIAL DE LA INTIMIDAD: VIH/SIDA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 717;
UPDATE public.course SET name = E'LA NATURALEZA EN MANOS DE LA SOCIEDAD', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 730;
UPDATE public.course SET name = E'EL SER HUMANO Y LA MASCULINIDAD', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 733;
UPDATE public.course SET name = E'PATRIMONIO IDENTIDAD Y DESARROLLO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 734;
UPDATE public.course SET name = E'DESARROLLO DEL ARTE EN COSTA RICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 735;
UPDATE public.course SET name = E'JORGE LUIS BORGES: LA VIDA COMO LITERATURA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 736;
UPDATE public.course SET name = E'EL NUEVO APRENDIZAJE - ENFOQUE DE LA PROGRAMACIÓN NEUROLINGÜÍSTICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 751;
UPDATE public.course SET name = E'GARCÍA MÁRQUEZ Y EL REALISMO MÁGICO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 763;
UPDATE public.course SET name = E'LITERATURA FANTÁSTICA: TOLKIEN Y EL SEÑOR DE LOS ANILLOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 765;
UPDATE public.course SET name = E'ASPECTOS BÁSICOS SOBRE LA LEY CONTRA LA VIOLENCIA DOMESTICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 766;
UPDATE public.course SET name = E'INTRODUCCIÓN A LA FILOSOFÍA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 769;
UPDATE public.course SET name = E'HISTORIA DEL PENSAMIENTO COSTARRICENSE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 771;
UPDATE public.course SET name = E'LITERATURA CONTEMPORÁNEA DE AMÉRICA LATINA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 772;
UPDATE public.course SET name = E'HISTORIA DEL ARTE UNIVERSAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 777;
UPDATE public.course SET name = E'MITOLOGÍA MUNDIAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 778;
UPDATE public.course SET name = E'MENTE Y CEREBRO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 783;
UPDATE public.course SET name = E'DE FREUD AL FENÓMENO BIO-PSICO-SOCIAL DE LA SEXUALIDAD', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 794;
UPDATE public.course SET name = E'SEXO Y GÉNERO, EN LA VIDA Y EL AMOR', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 795;
UPDATE public.course SET name = E'BRUJAS, HADAS Y FANTASMAS EN SHAKESPEARE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 799;
UPDATE public.course SET name = E'LOS MITOS Y BÚSQUEDA DEL HÉROE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 802;
UPDATE public.course SET name = E'RECRECÍAN, OCIO, ESPARCIMIENTO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 804;
UPDATE public.course SET name = E'GRAFITI: DE LAS CALLES A LA LITERATURA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 806;
UPDATE public.course SET name = E'LA ENSEÑANZA DE LA LENGUA INGLESA Y SU PARALELISMO CON DESARROLLO ECONÓMICO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 810;
UPDATE public.course SET name = E'ANÁLISIS DEL INFALIBLE SHERLOCK HOLMES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 815;
UPDATE public.course SET name = E'SITUACIÓN ENERGÉTICA MUNDIAL. OPCIONES DE COSTA RICA A CORTO Y MEDIANO PLAZO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 821;
UPDATE public.course SET name = E'APRENDIZAJE Y COGNICIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 823;
UPDATE public.course SET name = E'FACTORES PSICOSOCIALES DE LA SALUD MENTAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 826;
UPDATE public.course SET name = E'ARTE PRECOLOMBINO DE COSTA RICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 829;
UPDATE public.course SET name = E'LENGUAJE AUDIOVISUAL: PRODUCCIÓN Y REALIZACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 830;
UPDATE public.course SET name = E'LA CULTURA DE LA ALTERIDAD: COMO RESPUESTA, REALIDAD ACTUAL COSTA RICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 833;
UPDATE public.course SET name = E'DERECHOS FUNDAMENTALES Y SOCIEDAD DE LA INFORMACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 835;
UPDATE public.course SET name = E'INTERNET, VENTANA DE POSTMODERNIDAD', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 838;
UPDATE public.course SET name = E'INTRODUCCIÓN AL PENSAMIENTO CRITICO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 839;
UPDATE public.course SET name = E'FUNDAMENTOS DE DESARROLLO SOSTENIBLE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 846;
UPDATE public.course SET name = E'HABLEMOS DE DISCAPACIDAD', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 852;
UPDATE public.course SET name = E'ANÁLISIS, APRECIACIÓN Y CRÍTICA DE LA DANZA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 853;
UPDATE public.course SET name = E'SEXO Y EROTISMO EN LA LITERATURA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 858;
UPDATE public.course SET name = E'EL CUENTO POLICIAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 859;
UPDATE public.course SET name = E'HACIA UNA LECTURA CRÍTICA DE LOS MEDIOS: ¿CÓMO APRENDER A ENFRENTARSE MEJOR A LO QUE NOS DICEN LOS MEDIOS?', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 860;
UPDATE public.course SET name = E'LITERATURA Y CULTURA: DIALÉCTICA A PARTIR DE TEXTOS LATINOAMERICANOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 862;
UPDATE public.course SET name = E'CARMEN LYRA: UNA PENSADORA QUE SE ADELANTÓ A SU ÉPOCA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 864;
UPDATE public.course SET name = E'EL LEGADO DE LOS SABIOS: UN ACERCAMIENTO A LA FILOSOFÍA PRÁCTICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 865;
UPDATE public.course SET name = E'MOVIMIENTOS ESTUDIANTILES UNIVERSITARIOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 867;
UPDATE public.course SET name = E'FILOSOFÍA Y LOS FEMINISMOS DESDE LA COTIDIANIDAD', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 869;
UPDATE public.course SET name = E'EL EROTISMO EN LA LITERATURA: UN ANÁLISIS DE "CUENTOS SUCIOS" Y OTROS RELATOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 871;
UPDATE public.course SET name = E'ANÁLISIS CRITICO DE LA REVOLUCIÓN VIRTUAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 872;
UPDATE public.course SET name = E'ESTADO O MERCADO: EL ORIGEN DE LA DISCUSIÓN IDEOLÓGICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 875;
UPDATE public.course SET name = E'AMÉRICA DEL SUR EN LA NARRATIVA CORTA CONTEMPORÁNEA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 876;
UPDATE public.course SET name = E'TRES NATURALISTAS "COSTARRICENSES" ALFARO, TORRES, SKUTCH', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 879;
UPDATE public.course SET name = E'LA DIVERSIDAD CULTURAL EN EL CARIBE COSTARRICENSE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 882;
UPDATE public.course SET name = E'LA CONDICIÓN HUMANA EN NUESTRA ÉPOCA: ÉTICA Y DERECHOS HUMANOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 887;
UPDATE public.course SET name = E'NUEVAS FORMAS DE CRIMEN ORGANIZADO Y VIOLACIÓN DE LOS DERECHOS HUMANOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 889;
UPDATE public.course SET name = E'LITERATURA DEL BANANO EN CENTROAMÉRICA Y EL CARIBE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 890;
UPDATE public.course SET name = E'INTERACCIÓN COMUNICATIVA Y ADQUISICIÓN DEL LENGUAJE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 892;
UPDATE public.course SET name = E'LA MÚSICA NOS DEFINE: VISIÓN DESDE LA ETNOMUSICOLOGÍA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 894;
UPDATE public.course SET name = E'FORMAS ACTUALES DE VIOLENCIA EN LAS RELACIONES DE NOVIAZGO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 897;
UPDATE public.course SET name = E'INTRODUCCIÓN A LA FILOSOFÍA A TRAVÉS DEL CINE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 898;
UPDATE public.course SET name = E'EL UNIVERSO DE STAR WARS: ENTRE LA CIENCIA FICCIÓN, LA POLÍTICA Y LA MITOLOGÍA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 899;
UPDATE public.course SET name = E'CONSTRUCCIÓN DE LA ASTRONOMÍA MODERNA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 901;
UPDATE public.course SET name = E'ADECUADO MANEJO DEL CONFLICTO HUMANO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 905;
UPDATE public.course SET name = E'PERVIVENCIA DE MODELOS FEMENINOS: DE LA GRECIA ANTIGUA A LA ACTUALIDAD', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 907;
UPDATE public.course SET name = E'HERRAMIENTAS PARA LA PUESTA EN VALOR Y LA PLANIFICACIÓN SOSTENIBLE DE ESPACIOS CON PATRIMONIO NATURAL Y CULTURAL RELEVANTE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 909;
UPDATE public.course SET name = E'VULNERABILIDAD: PERSONAS MAYORES, ENVEJECIMIENTO Y FINAL DE LA VIDA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 910;
UPDATE public.course SET name = E'RELIGIÓN, ESPIRITUALIDADES Y ÉTICA MUNDIAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 911;
UPDATE public.course SET name = E'POSVERDAD, REDES SOCIALES Y NOTICIAS FALSAS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 912;
UPDATE public.course SET name = E'MÚSICA REGGAE COMO PATRIMONIO INMATERIAL DE LA HUMANIDAD', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 915;
UPDATE public.course SET name = E'LA DIMENSIÓN HUMANA DE LA INVESTIGACIÓN CUALITATIVA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 916;
UPDATE public.course SET name = E'DE MONSTRUOS Y VAMPIROS: EL HORROR GÓTICO EN FRANKENSTEIN Y DRÁCULA EN LA ÉPOCA VICTORIANA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 919;
UPDATE public.course SET name = E'MANIFESTACIONES DEL RACISMO EN COSTA RICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 920;
UPDATE public.course SET name = E'VENTILACIÓN INDUSTRIAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 985;
UPDATE public.course SET name = E'NEUMÁTICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 988;
UPDATE public.course SET name = E'PROCESAMIENTO DIGITAL DE IMÁGENES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1106;
UPDATE public.course SET name = E'DISEÑO DE EXPERIMENTOS COMPUTACIONALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1111;
UPDATE public.course SET name = E'INNOVACIÓN Y CREATIVIDAD', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1116;
UPDATE public.course SET name = E'INTRODUCCIÓN AL RECONOCIMIENTO DE PATRONES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1117;
UPDATE public.course SET name = E'SIMULACIÓN DE SISTEMAS NATURALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1119;
UPDATE public.course SET name = E'INTRODUCCIÓN A LA BIOLOGÍA MOLECULAR COMPUTACIONAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1121;
UPDATE public.course SET name = E'PROGRAMACIÓN COMPETITIVA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1122;
UPDATE public.course SET name = E'CRIPTOGRAFÍA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1123;
UPDATE public.course SET name = E'VISUALIZACIÓN DE INFORMACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1127;
UPDATE public.course SET name = E'INTRODUCCIÓN AL DESARROLLO DE PAGINAS WEB', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1128;
UPDATE public.course SET name = E'SISTEMAS DE INFORMACIÓN GEOGRÁFICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1129;
UPDATE public.course SET name = E'INTRODUCCIÓN A LOS GRÁFICOS POR COMPUTADOR', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1130;
UPDATE public.course SET name = E'RECUPERACIÓN DE INFORMACIÓN TEXTUAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1131;
UPDATE public.course SET name = E'SIMULACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1132;
UPDATE public.course SET name = E'COMERCIO ELECTRÓNICO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1134;
UPDATE public.course SET name = E'DESARROLLO DE APLICACIONES PARA DISPOSITIVOS MÓVILES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1137;
UPDATE public.course SET name = E'DISEÑO DE JUEGOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1139;
UPDATE public.course SET name = E'INTRODUCCIÓN A LA REALIDAD VIRTUAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1143;
UPDATE public.course SET name = E'INTRODUCCIÓN AL ANÁLISIS DE DATOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1146;
UPDATE public.course SET name = E'ALMACENES DE DATOS Y PROCESAMIENTO OLAP', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1148;
UPDATE public.course SET name = E'DISEÑO DE EXPERIENCIAS DE APRENDIZAJE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1150;
UPDATE public.course SET name = E'PROCESAMIENTO Y ANÁLISIS DE IMÁGENES DIGITALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1335;
UPDATE public.course SET name = E'INTRODUCCIÓN AL RECONOCIMIENTO DE PATRONES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1336;
UPDATE public.course SET name = E'PROCESAMIENTO DIGITAL DE SEÑALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1339;
UPDATE public.course SET name = E'INTRODUCCIÓN AL DISEÑO DE CIRCUITOS INTEGRADOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1340;
UPDATE public.course SET name = E'VERIFICACIÓN FUNCIONAL DE CIRCUITOS INTEGRADOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1341;
UPDATE public.course SET name = E'GRÁFICOS POR COMPUTADORA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1342;
UPDATE public.course SET name = E'SISTEMAS FOTOVOLTAICOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1346;
UPDATE public.course SET name = E'INGENIERÍA DE PRUEBAS PARA CIRCUITOS INTEGRADOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1347;
UPDATE public.course SET name = E'APRENDIZAJE AUTOMÁTICO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1348;
UPDATE public.course SET name = E'INTRODUCCIÓN A SISTEMAS AEROESPACIALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1349;
UPDATE public.course SET name = E'TALLER DE SISTEMAS EMBEBIDOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1354;
UPDATE public.course SET name = E'TALLER DE INSTRUMENTACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1355;
UPDATE public.course SET name = E'TALLER DE CIRCUITOS ELECTRÓNICOS PARA SISTEMAS ENERGÉTICOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1356;
UPDATE public.course SET name = E'FÍSICA DE PLASMAS Y SUS APLICACIONES I', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1423;
UPDATE public.course SET name = E'TÓPICOS DE GEOMETRÍA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1703;
UPDATE public.course SET name = E'TEORÍA DE CONJUNTOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1704;
UPDATE public.course SET name = E'ESTADÍSTICA INFERENCIAL Y ANÁLISIS DE DATOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1713;
UPDATE public.course SET name = E'PROGRAMACIÓN LINEAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1715;
UPDATE public.course SET name = E'CURVAS Y SUPERFICIES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1716;
UPDATE public.course SET name = E'INVESTIGACIÓN DE OPERACIONES II', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1769;
UPDATE public.course SET name = E'EVALUACIÓN DE PROYECTOS DE INVERSIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1772;
UPDATE public.course SET name = E'GESTIÓN POR PROCESOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1773;
UPDATE public.course SET name = E'LOGÍSTICA DE ALMACENES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1774;
UPDATE public.course SET name = E'DISEÑO DE PUESTOS DE TRABAJO Y HERRAMIENTAS ERGONÓMICAS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1775;
UPDATE public.course SET name = E'TÓPICOS AVANZADOS DE PRODUCCIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1788;
UPDATE public.course SET name = E'AUTOMATIZACIÓN DE ALMACENES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1790;
UPDATE public.course SET name = E'PRODUCCIÓN INDUSTRIAL MÁS LIMPIA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1791;
UPDATE public.course SET name = E'SIMULACIÓN INDUSTRIAL II', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1792;
UPDATE public.course SET name = E'INTRODUCCIÓN AL DISEÑO DE SERVICIOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1897;
UPDATE public.course SET name = E'DISEÑO E IMPLEMENTACIÓN DE SU PROPIO WEB-SITE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1898;
UPDATE public.course SET name = E'INTRODUCCIÓN AL DISEÑO PARA LA INNOVACIÓN SOCIAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 1899;
UPDATE public.course SET name = E'DISEÑO DE REDES PARA ABASTECIMIENTO DE AGUA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2047;
UPDATE public.course SET name = E'ADMINISTRACIÓN DE LA MECANIZACIÓN AGRÍCOLA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2049;
UPDATE public.course SET name = E'SISTEMA DE INFORMACIÓN GEOGRÁFICO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2059;
UPDATE public.course SET name = E'TECNOLOGÍAS EN AMBIENTES PROTEGIDOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2060;
UPDATE public.course SET name = E'EVALUACIÓN DE IMPACTO AMBIENTAL I', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2201;
UPDATE public.course SET name = E'FAUNA SILVESTRE I', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2214;
UPDATE public.course SET name = E'EVALUACIÓN DE IMPACTO AMBIENTAL II', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2216;
UPDATE public.course SET name = E'DENDROLOGÍA TROPICAL II', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2219;
UPDATE public.course SET name = E'ECOLOGÍA Y MANEJO DE BOSQUES SECUNDARIOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2220;
UPDATE public.course SET name = E'PRODUCTOS NO MADERABLES DEL BOSQUE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2222;
UPDATE public.course SET name = E'SISTEMAS DE INFORMACIÓN GEOGRÁFICA II', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2224;
UPDATE public.course SET name = E'SISTEMAS DE SENSORES REMOTOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2225;
UPDATE public.course SET name = E'ECOLOGÍA DE LAS INTERACCIONES PLANTA-ANIMAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2227;
UPDATE public.course SET name = E'INVASIONES BIOLÓGICAS: ECOLOGÍA, MANEJO Y CONTROL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2228;
UPDATE public.course SET name = E'MODELACIÓN HIDROLÓGICA EN CUENCAS HIDROGRÁFICAS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2229;
UPDATE public.course SET name = E'SILVICULTURA DE PRECISIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2230;
UPDATE public.course SET name = E'BIOESTADÍSTICA CON R', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2231;
UPDATE public.course SET name = E'ECOLOGÍA Y MANEJO DE BOSQUE SECUNDARIO PARA LA CONSERVACIÓN Y RESTAURACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2233;
UPDATE public.course SET name = E'REGENERACIÓN DE BOSQUE NATURAL PARA LA CONSSERVACIÓN Y RESTAURACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2234;
UPDATE public.course SET name = E'SISTEMAS DE INFORMACIÓN GEOGRÁFICA II PARA LA CONSERVACIÓN Y RESTAURACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2235;
UPDATE public.course SET name = E'SISTEMAS DE SENSORES REMOTOS PARA LA CONSERVACIÓN Y RESTAURACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2236;
UPDATE public.course SET name = E'DENTROLOGÍA TROPICAL II PARA LA CONSERVACIÓN Y RESTAURACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2238;
UPDATE public.course SET name = E'FAUNA SILVESTRE II', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2246;
UPDATE public.course SET name = E'ANATOMÍA E IDENTIFICACIÓN DE LA MADERA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2260;
UPDATE public.course SET name = E'EVALUACIÓN DE PLANTACIONES FORESTALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2268;
UPDATE public.course SET name = E'MEJORAMIENTO GENÉTICO FORESTAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2304;
UPDATE public.course SET name = E'EPIDOMETRÍA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2305;
UPDATE public.course SET name = E'ECOLOGÍA FORESTAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2308;
UPDATE public.course SET name = E'MANEJO DE BOSQUE NATURAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2309;
UPDATE public.course SET name = E'REGENERACIÓN NATURAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2311;
UPDATE public.course SET name = E'SISTEMAS DE INFORMACIÓN GEOGRÁFICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2317;
UPDATE public.course SET name = E'PROPIEDADES DE LA MADERA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2319;
UPDATE public.course SET name = E'ESTRUCTURAS DE MADERA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2320;
UPDATE public.course SET name = E'SECADO Y PRESERVACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2321;
UPDATE public.course SET name = E'TECNOLOGÍA DE DIÁMETROS MENORES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2322;
UPDATE public.course SET name = E'BIOENERGÍA Y SUBPRODUCTOS FORESTALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2323;
UPDATE public.course SET name = E'BIODETERIORO DE LA MADERA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2324;
UPDATE public.course SET name = E'ESPÍRITU EMPRENDEDOR Y CREACIÓN DE EMPRESAS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2463;
UPDATE public.course SET name = E'ADMINISTRACIÓN DE PROYECTOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2464;
UPDATE public.course SET name = E'MÉTODOS CUANTITATIVOS PARA ADMINISTRACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2465;
UPDATE public.course SET name = E'GESTIÓN DE ORGANIZACIONES DE ECONOMÍA SOCIAL SOLIDARIA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2467;
UPDATE public.course SET name = E'IMPUESTOS EN COSTA RICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2468;
UPDATE public.course SET name = E'PLANEACIÓN DEL MERCADEO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2469;
UPDATE public.course SET name = E'NEUROMARKETING COMO ESTRATEGIA EMPRESARIAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2470;
UPDATE public.course SET name = E'ANALÍTICA DE NEGOCIO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2471;
UPDATE public.course SET name = E'NEUROMARKETING Y NEUROCIENCIA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2472;
UPDATE public.course SET name = E'GESTIÓN DE LA INNOVACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2473;
UPDATE public.course SET name = E'LOGÍSTICA Y ADMINISTRACIÓN DE LA CADENA DE ABASTECIMIENTO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2474;
UPDATE public.course SET name = E'CREATIVIDAD E INNOVACIÓN EMPRESARIAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2480;
UPDATE public.course SET name = E'DISEÑO DE DASHBOARDS DE CONTROL PARA ANÁLISIS DE INFORMACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2567;
UPDATE public.course SET name = E'HABILIDADES DIRECTIVAS PARA EL ADMINISTRADOR DE TECNOLOGÍA DE LA INFORMACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2568;
UPDATE public.course SET name = E'FUNDAMENTOS DE TRANSFORMACIÓN DIGITAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2569;
UPDATE public.course SET name = E'DESARROLLO ÁGIL DE APLICACIONES WEB', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2570;
UPDATE public.course SET name = E'BLOCKCHAIN Y APLICACIONES DESCENTRALIZADAS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2593;
UPDATE public.course SET name = E'INTELIGENCIA ARTIFICIAL EN SISTEMAS DE INFORMACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2595;
UPDATE public.course SET name = E'GESTIÓN DE CERTIFICACIONES EN AGRONEGOCIOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2729;
UPDATE public.course SET name = E'ANÁLISIS DE FALLAS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2780;
UPDATE public.course SET name = E'BIOMATERIALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2790;
UPDATE public.course SET name = E'TECNOLOGÍA DE RECUBRIMIENTOS Y CAPAS DELGADAS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2796;
UPDATE public.course SET name = E'FUNDAMENTOS EN ADMINISTRACIÓN DE PROYECTOS EN INGENIERÍA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2886;
UPDATE public.course SET name = E'SISTEMAS DE PROTECCIÓN CONTRA INCENDIOS A BASE DE AGUA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2887;
UPDATE public.course SET name = E'SISTEMAS DE CONTROL AUTOMÁTICO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2888;
UPDATE public.course SET name = E'REDES INTELIGENTES DE DISTRIBUCIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2889;
UPDATE public.course SET name = E'SISTEMA DE PUESTA A TIERRA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2891;
UPDATE public.course SET name = E'SISTEMAS DE REFRIGERACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2892;
UPDATE public.course SET name = E'INTRODUCCIÓN A LOS SISTEMAS EMBEBIDOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2985;
UPDATE public.course SET name = E'SOA41D: ARQUITECTURA ORIENTADA A SERVICIOS APLICADA A SISTEMAS EMERGENTES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 2993;
UPDATE public.course SET name = E'ROBÓTICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3007;
UPDATE public.course SET name = E'INTELIGENCIA ARTIFICIAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3075;
UPDATE public.course SET name = E'SIMULACIÓN PROCESOS INDUSTRIALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3082;
UPDATE public.course SET name = E'SISTEMAS DE VISIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3085;
UPDATE public.course SET name = E'MEMS-NEMS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3086;
UPDATE public.course SET name = E'SISTEMAS INTEGRADOS DE GESTIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3108;
UPDATE public.course SET name = E'SEMINARIO DE ERGONOMÍA APLICADA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3110;
UPDATE public.course SET name = E'BIOLOGÍA GENERAL PARA INGENIERÍA AMBIENTAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3163;
UPDATE public.course SET name = E'ANÁLISIS TOPOGRÁFICO EN INGENIERÍA AMBIENTAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3171;
UPDATE public.course SET name = E'ADMINISTRACIÓN DE ENERGÍA EN LA INDUSTRIA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3204;
UPDATE public.course SET name = E'FÍSICA AMBIENTAL DE SUELOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3212;
UPDATE public.course SET name = E'TOXICOLOGÍA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3219;
UPDATE public.course SET name = E'INTRODUCCIÓN A LA CIENCIA DE LOS POLÍMEROS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3222;
UPDATE public.course SET name = E'CAMBIO CLIMÁTICO, ADAPTACIÓN Y MITIGACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3223;
UPDATE public.course SET name = E'PROBLEMAS AMBIENTALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3224;
UPDATE public.course SET name = E'INGENIERÍA URBANA SOSTENIBLE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3225;
UPDATE public.course SET name = E'ENERGÍAS RENOVABLES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3228;
UPDATE public.course SET name = E'TOXICOLOGÍA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3229;
UPDATE public.course SET name = E'BIOTECNOLOGÍA Y GENÉTICA HUMANA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3295;
UPDATE public.course SET name = E'MANEJO BIOTECNOLÓGICO DE CULTIVOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3299;
UPDATE public.course SET name = E'INGENIERÍA GENÉTICA DE PLANTAS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3301;
UPDATE public.course SET name = E'BIOINFORMÁTICA PARA BIOTECNOLOGÍA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3304;
UPDATE public.course SET name = E'FUNDAMENTOS DE ANATOMÍA Y DESARROLLO ANIMAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3305;
UPDATE public.course SET name = E'BACTERIOLOGÍA APLICADA A LA BIOTECNOLOGÍA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3306;
UPDATE public.course SET name = E'FUNDAMENTOS DEL CULTIVO DE CÉLULAS ANIMALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3307;
UPDATE public.course SET name = E'PROCESOS BIOTECNOLÓGICOS CON EL EMPLEO DE HONGOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3309;
UPDATE public.course SET name = E'INTRODUCCIÓN A LA FITOQUÍMICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3310;
UPDATE public.course SET name = E'PROPIEDAD INTELECTUAL, INNOVACIÓN Y BIOTECNOLOGÍA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3311;
UPDATE public.course SET name = E'MÉTODOS MOLECULARES DE MICROBIOLOGÍA AMBIENTAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3312;
UPDATE public.course SET name = E'FUNDAMENTOS DE FISIOLOGÍA HUMANA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3313;
UPDATE public.course SET name = E'VIROLOGÍA MOLECULAR DE PLANTAS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3314;
UPDATE public.course SET name = E'INSECTOS EN BIOTECNOLOGÍA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3315;
UPDATE public.course SET name = E'CONTROL Y ASEGURAMIENTO DE CALIDAD PARA LA INDUSTRIA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3316;
UPDATE public.course SET name = E'CONTROL DE CALIDAD APLICADO A LAS EMPRESAS DE MANUFACTURA DE DISPOSITIVOS MÉDICOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3408;
UPDATE public.course SET name = E'ESTADÍSTICA AVANZADA PARA BIOTECNOLOGÍA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3409;
UPDATE public.course SET name = E'BIOINFORMÁTICA APLICADA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3410;
UPDATE public.course SET name = E'MODELO DE NEGOCIOS DE EMPRESAS BIOTECNOLÓGICAS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3411;
UPDATE public.course SET name = E'INTRODUCCIÓN A LA PROGRAMACIÓN PARA BIOTECNOLOGÍA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3414;
UPDATE public.course SET name = E'AUDITORÍAS A SISTEMAS DE CALIDAD', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3415;
UPDATE public.course SET name = E'BIOTECNOLOGÍA AMBIENTAL PARA EL DESARROLLO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3416;
UPDATE public.course SET name = E'GERENCIA TÉCNICA DE LA CALIDAD BASADA EN INTE-ISO 17025:2017', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3417;
UPDATE public.course SET name = E'VALORACIÓN DE EMPRESAS EN MARCHA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3425;
UPDATE public.course SET name = E'PRINCIPIOS DE INVERSIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3426;
UPDATE public.course SET name = E'GESTIÓN DEL RIESGO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3429;
UPDATE public.course SET name = E'COMERCIO Y MARKETING DIGITAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3433;
UPDATE public.course SET name = E'GESTIÓN DE PROYECTOS EN MERCADEO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3438;
UPDATE public.course SET name = E'EJERCICIO DE LA PROFESIÓN CONTABLE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3466;
UPDATE public.course SET name = E'CONTABILIDAD V', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3467;
UPDATE public.course SET name = E'ADMINISTRACIÓN DEL RIESGO Y EL CONTROL INTERNO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3599;
UPDATE public.course SET name = E'LOGÍSTICA INVERSA Y GESTIÓN AMBIENTAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3630;
UPDATE public.course SET name = E'SERVICIO AL CLIENTE EN LA CADENA DE ABASTECIMIENTO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3631;
UPDATE public.course SET name = E'DISEÑO DE SISTEMAS PRODUCTIVOS Y LOGÍSTICOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3632;
UPDATE public.course SET name = E'ALMACENAMIENTO ESBELTO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3634;
UPDATE public.course SET name = E'DISEÑO COMERCIAL PARA DISTRIBUCIÓN/RETAIL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3635;
UPDATE public.course SET name = E'COMPETENCIAS GERENCIALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3644;
UPDATE public.course SET name = E'EVALUACIÓN DE PROYECTOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3648;
UPDATE public.course SET name = E'ADMINISTRACIÓN DE PROYECTOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3650;
UPDATE public.course SET name = E'MANTENIMIENTO BASADO EN CONDICIONES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3660;
UPDATE public.course SET name = E'GESTIÓN DE SISTEMAS DE CLIMATIZACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3676;
UPDATE public.course SET name = E'ENTORNO ECONÓMICO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3679;
UPDATE public.course SET name = E'ENERGÍA E INDUSTRIA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3700;
UPDATE public.course SET name = E'FISIOLOGÍA DE ARBOLES Y BOSQUES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3746;
UPDATE public.course SET name = E'SILVICULTURA DE PRECISIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3747;
UPDATE public.course SET name = E'FUNDAMENTOS ECOLÓGICOS PARA LA CONSERVACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3748;
UPDATE public.course SET name = E'PATOLOGÍA FORESTAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3749;
UPDATE public.course SET name = E'AUDITORÍA DE TECNOLOGÍAS DE INFORMACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3760;
UPDATE public.course SET name = E'TECNOLOGÍAS EMERGENTES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3761;
UPDATE public.course SET name = E'CONSULTORÍA DE TECNOLOGÍAS DE INFORMACIÓN', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3762;
UPDATE public.course SET name = E'HABILIDADES GERENCIALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3764;
UPDATE public.course SET name = E'AMBIENTE Y DESARROLLO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3837;
UPDATE public.course SET name = E'DISEÑO DE EXPERIMENTOS EN LA MANUFACTURA DE DISPOSITIVOS MÉDICOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3862;
UPDATE public.course SET name = E'DISEÑO Y FABRICACIÓN DE PROTOTIPOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3863;
UPDATE public.course SET name = E'PROCESAMIENTO DE METALES EN LA INDUSTRIA DE DISPOSITIVOS MÉDICOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3864;
UPDATE public.course SET name = E'VALIDACIONES EN LA INDUSTRIA MEDICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3865;
UPDATE public.course SET name = E'MODELACIÓN Y SIMULACIÓN DE DISPOSITIVOS MÉDICOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3866;
UPDATE public.course SET name = E'BIOCOMPATIBILIDAD DE LOS MATERIALES UTILIZADOS EN DISPOSITIVOS MÉDICOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3868;
UPDATE public.course SET name = E'DISEÑO ELECTROMECÁNICO DE DISPOSITIVOS MÉDICOS ASISTIDO POR COMPUTADORA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3869;
UPDATE public.course SET name = E'TECNOLOGÍA DE SOLDADURA Y UNIONES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3870;
UPDATE public.course SET name = E'RESOLUCIÓN DE PROBLEMAS EN LA INDUSTRIA MEDICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3871;
UPDATE public.course SET name = E'TECNOLOGÍA ELECTRÓNICA EN LOS DISPOSITIVOS MÉDICOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3872;
UPDATE public.course SET name = E'TECNOLOGÍA DE RECUBRIMIENTO APLICADA A DISPOSITIVOS MÉDICOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3873;
UPDATE public.course SET name = E'MEJORA CONTINUA EN LA INDUSTRIA MÉDICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3874;
UPDATE public.course SET name = E'HERRAMIENTAS CAD CAM', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3876;
UPDATE public.course SET name = E'INNOVACIÓN EN LA EDUCACIÓN TÉCNICA Y FORMACIÓN PROFESIONAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3907;
UPDATE public.course SET name = E'DISEÑO AVANZADO CON FPGAS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3930;
UPDATE public.course SET name = E'ARQUITECTURA DE PROCESAMIENTO PARALELO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3966;
UPDATE public.course SET name = E'AUTOMATIZACIÓN DEL DISEÑO ELECTRÓNICO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 3967;
UPDATE public.course SET name = E'INGENIERÍA DE TRANSITO Y SEGURIDAD VIAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4021;
UPDATE public.course SET name = E'INGENIERÍA DE TRANSITO Y SEGURIDAD VIAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4023;
UPDATE public.course SET name = E'DIRECCIÓN DE PROYECTOS VIALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4041;
UPDATE public.course SET name = E'ANÁLISIS DE MANUFACTURA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4087;
UPDATE public.course SET name = E'LOGÍSTICA INVERSA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4094;
UPDATE public.course SET name = E'ROBÓTICA INDUSTRIAL Y ENSAMBLE FLEXIBLE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4099;
UPDATE public.course SET name = E'SIMULADORES DE PROCESOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4101;
UPDATE public.course SET name = E'GESTIÓN DE RECURSOS HUMANOS Y CALIDAD', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4102;
UPDATE public.course SET name = E'FÍSICA DE PLASMAS PARA INGENIERÍA II', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4136;
UPDATE public.course SET name = E'APLICACIONES DE FÍSICA EN BIOLOGÍA Y MEDICINA I', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4137;
UPDATE public.course SET name = E'TÓPICOS DE ASTRONOMÍA Y ASTROFÍSICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4138;
UPDATE public.course SET name = E'LABORATORIO DE METROLOGÍA II', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4140;
UPDATE public.course SET name = E'EXPLORACIÓN Y ANÁLISIS ESTADÍSTICO DE DATOS EXPERIMENTALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4141;
UPDATE public.course SET name = E'DINÁMICA DE ESPINES Y RESONANCIA MAGNÉTICA NUCLEAR', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4142;
UPDATE public.course SET name = E'MODELADO PREDICTIVO APLICADO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4143;
UPDATE public.course SET name = E'GESTIÓN ESTRATÉGICA DE RECURSOS NATURALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4166;
UPDATE public.course SET name = E'DESARROLLO RURAL SOSTENIBLE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4169;
UPDATE public.course SET name = E'SISTEMAS DE GESTIÓN AMBIENTAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4171;
UPDATE public.course SET name = E'ASPECTOS MOLECULARES DE LA FITOPATOLOGÍA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4172;
UPDATE public.course SET name = E'INGENIERÍA GENÉTICA Y BIOSEGURIDAD', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4173;
UPDATE public.course SET name = E'MANEJO Y GESTIÓN DE CUENCAS HIDROGRÁFICAS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4174;
UPDATE public.course SET name = E'MANEJO Y CONSERVACIÓN DE SUELOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4176;
UPDATE public.course SET name = E'AGUAS SUBTERRÁNEAS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4186;
UPDATE public.course SET name = E'TÉCNICAS DE IDENTIFICACIÓN Y VALORACIÓN DEL DAÑO AMBIENTAL', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4190;
UPDATE public.course SET name = E'MEDICIÓN Y COMPENSACIÓN DE LA HUELLA DE CARBONO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4191;
UPDATE public.course SET name = E'AUTOMATIZACIÓN DE ALMACENES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4246;
UPDATE public.course SET name = E'FÍSICA PARA AGRONOMÍA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4270;
UPDATE public.course SET name = E'SISTEMAS AGRONÓMICOS DE INFORMACIÓN GEOGRÁFICA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4327;
UPDATE public.course SET name = E'DISEÑO Y CONSTRUCCIÓN DE INFRAESTRUCTURA AGROPECUARIA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4328;
UPDATE public.course SET name = E'CULTIVOS PROTEGIDOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4333;
UPDATE public.course SET name = E'GESTIÓN DE CALIDAD AGROALIMENTARIA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4334;
UPDATE public.course SET name = E'INTRODUCCIÓN A LA NEMATOLOGÍA', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4335;
UPDATE public.course SET name = E'SISTEMAS AGROFORESTALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4337;
UPDATE public.course SET name = E'TECNOLOGÍA DE LECHE Y CARNE', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4341;
UPDATE public.course SET name = E'FUNDAMENTOS DE PROCESAMIENTO DE PRODUCTOS AGRÍCOLAS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4412;
UPDATE public.course SET name = E'GESTIÓN DE EQUIPOS ORGANIZACIONALES', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4541;
UPDATE public.course SET name = E'PSICOLOGÍA DEL CAPITAL HUMANO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4544;
UPDATE public.course SET name = E'CIENCIA DE LAS ESTRUCTURAS: APLICACIONES A LA ARQUITECTURA Y DISEÑO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4822;
UPDATE public.course SET name = E'LABORATORIO DE PROYECTOS X: DISEÑO ARQUITECTÓNICO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4828;
UPDATE public.course SET name = E'LABORATORIO DE PROYECTOS X: DISEÑO URBANO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4829;
UPDATE public.course SET name = E'BLOCKCHAIN Y LEDGER DISTRIBUIDOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4873;
UPDATE public.course SET name = E'SEGURIDAD EN SISTEMAS CIBERFÍSICOS', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4874;
UPDATE public.course SET name = E'DERECHO INFORMÁTICO', is_active = TRUE, deactivated_at = NULL, updated_at = NOW() WHERE id = 4875;

COMMIT;