/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/_index'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as VerifyEmailIndexRouteImport } from './routes/verify-email/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ScheduleIndexRouteImport } from './routes/schedule/index'
import { Route as ProfessorsIndexRouteImport } from './routes/professors/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as CurriculumIndexRouteImport } from './routes/curriculum/index'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as ProfessorsModerationRouteImport } from './routes/professors/moderation'
import { Route as ProfessorsProfessorIdRouteImport } from './routes/professors/$professorId'
import { Route as CurriculumCourseIdRouteImport } from './routes/curriculum/$courseId'

const IndexRoute = IndexRouteImport.update({
  id: '/_index',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailIndexRoute = VerifyEmailIndexRouteImport.update({
  id: '/verify-email/',
  path: '/verify-email/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorsIndexRoute = ProfessorsIndexRouteImport.update({
  id: '/professors/',
  path: '/professors/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumIndexRoute = CurriculumIndexRouteImport.update({
  id: '/curriculum/',
  path: '/curriculum/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ProfessorsModerationRoute = ProfessorsModerationRouteImport.update({
  id: '/professors/moderation',
  path: '/professors/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorsProfessorIdRoute = ProfessorsProfessorIdRouteImport.update({
  id: '/professors/$professorId',
  path: '/professors/$professorId',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumCourseIdRoute = CurriculumCourseIdRouteImport.update({
  id: '/curriculum/$courseId',
  path: '/curriculum/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/settings': typeof SettingsRouteRouteWithChildren
  '/': typeof IndexRoute
  '/curriculum/$courseId': typeof CurriculumCourseIdRoute
  '/professors/$professorId': typeof ProfessorsProfessorIdRoute
  '/professors/moderation': typeof ProfessorsModerationRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/curriculum/': typeof CurriculumIndexRoute
  '/login/': typeof LoginIndexRoute
  '/professors/': typeof ProfessorsIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/verify-email/': typeof VerifyEmailIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/curriculum/$courseId': typeof CurriculumCourseIdRoute
  '/professors/$professorId': typeof ProfessorsProfessorIdRoute
  '/professors/moderation': typeof ProfessorsModerationRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/curriculum': typeof CurriculumIndexRoute
  '/login': typeof LoginIndexRoute
  '/professors': typeof ProfessorsIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/signup': typeof SignupIndexRoute
  '/verify-email': typeof VerifyEmailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/settings': typeof SettingsRouteRouteWithChildren
  '/_index': typeof IndexRoute
  '/curriculum/$courseId': typeof CurriculumCourseIdRoute
  '/professors/$professorId': typeof ProfessorsProfessorIdRoute
  '/professors/moderation': typeof ProfessorsModerationRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/curriculum/': typeof CurriculumIndexRoute
  '/login/': typeof LoginIndexRoute
  '/professors/': typeof ProfessorsIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/verify-email/': typeof VerifyEmailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/settings'
    | '/'
    | '/curriculum/$courseId'
    | '/professors/$professorId'
    | '/professors/moderation'
    | '/settings/appearance'
    | '/settings/profile'
    | '/settings/security'
    | '/curriculum/'
    | '/login/'
    | '/professors/'
    | '/schedule/'
    | '/settings/'
    | '/signup/'
    | '/verify-email/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/curriculum/$courseId'
    | '/professors/$professorId'
    | '/professors/moderation'
    | '/settings/appearance'
    | '/settings/profile'
    | '/settings/security'
    | '/curriculum'
    | '/login'
    | '/professors'
    | '/schedule'
    | '/settings'
    | '/signup'
    | '/verify-email'
  id:
    | '__root__'
    | '/settings'
    | '/_index'
    | '/curriculum/$courseId'
    | '/professors/$professorId'
    | '/professors/moderation'
    | '/settings/appearance'
    | '/settings/profile'
    | '/settings/security'
    | '/curriculum/'
    | '/login/'
    | '/professors/'
    | '/schedule/'
    | '/settings/'
    | '/signup/'
    | '/verify-email/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  IndexRoute: typeof IndexRoute
  CurriculumCourseIdRoute: typeof CurriculumCourseIdRoute
  ProfessorsProfessorIdRoute: typeof ProfessorsProfessorIdRoute
  ProfessorsModerationRoute: typeof ProfessorsModerationRoute
  CurriculumIndexRoute: typeof CurriculumIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ProfessorsIndexRoute: typeof ProfessorsIndexRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  VerifyEmailIndexRoute: typeof VerifyEmailIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_index': {
      id: '/_index'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email/': {
      id: '/verify-email/'
      path: '/verify-email'
      fullPath: '/verify-email/'
      preLoaderRoute: typeof VerifyEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professors/': {
      id: '/professors/'
      path: '/professors'
      fullPath: '/professors/'
      preLoaderRoute: typeof ProfessorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/': {
      id: '/curriculum/'
      path: '/curriculum'
      fullPath: '/curriculum/'
      preLoaderRoute: typeof CurriculumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/professors/moderation': {
      id: '/professors/moderation'
      path: '/professors/moderation'
      fullPath: '/professors/moderation'
      preLoaderRoute: typeof ProfessorsModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professors/$professorId': {
      id: '/professors/$professorId'
      path: '/professors/$professorId'
      fullPath: '/professors/$professorId'
      preLoaderRoute: typeof ProfessorsProfessorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/$courseId': {
      id: '/curriculum/$courseId'
      path: '/curriculum/$courseId'
      fullPath: '/curriculum/$courseId'
      preLoaderRoute: typeof CurriculumCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SettingsRouteRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  IndexRoute: IndexRoute,
  CurriculumCourseIdRoute: CurriculumCourseIdRoute,
  ProfessorsProfessorIdRoute: ProfessorsProfessorIdRoute,
  ProfessorsModerationRoute: ProfessorsModerationRoute,
  CurriculumIndexRoute: CurriculumIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  ProfessorsIndexRoute: ProfessorsIndexRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  VerifyEmailIndexRoute: VerifyEmailIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
