/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/_index'
import { Route as VerifyEmailIndexRouteImport } from './routes/verify-email/index'
import { Route as SignupIndexRouteImport } from './routes/signup/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AppIndexRouteImport } from './routes/app/_index'
import { Route as AppSettingsRouteRouteImport } from './routes/app/settings/route'
import { Route as AppSettingsIndexRouteImport } from './routes/app/settings/index'
import { Route as AppScheduleIndexRouteImport } from './routes/app/schedule/index'
import { Route as AppProfessorsIndexRouteImport } from './routes/app/professors/index'
import { Route as AppCurriculumIndexRouteImport } from './routes/app/curriculum/index'
import { Route as AppSettingsSecurityRouteImport } from './routes/app/settings/security'
import { Route as AppSettingsProfileRouteImport } from './routes/app/settings/profile'
import { Route as AppSettingsAppearanceRouteImport } from './routes/app/settings/appearance'
import { Route as AppSettingsLayoutRouteImport } from './routes/app/settings/_layout'
import { Route as AppProfessorsModerationRouteImport } from './routes/app/professors/moderation'
import { Route as AppProfessorsProfessorIdRouteImport } from './routes/app/professors/$professorId'

const IndexRoute = IndexRouteImport.update({
  id: '/_index',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailIndexRoute = VerifyEmailIndexRouteImport.update({
  id: '/verify-email/',
  path: '/verify-email/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupIndexRoute = SignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/_index',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRouteRoute = AppSettingsRouteRouteImport.update({
  id: '/app/settings',
  path: '/app/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppScheduleIndexRoute = AppScheduleIndexRouteImport.update({
  id: '/app/schedule/',
  path: '/app/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfessorsIndexRoute = AppProfessorsIndexRouteImport.update({
  id: '/app/professors/',
  path: '/app/professors/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCurriculumIndexRoute = AppCurriculumIndexRouteImport.update({
  id: '/app/curriculum/',
  path: '/app/curriculum/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsSecurityRoute = AppSettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsProfileRoute = AppSettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsAppearanceRoute = AppSettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppSettingsLayoutRoute = AppSettingsLayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => AppSettingsRouteRoute,
} as any)
const AppProfessorsModerationRoute = AppProfessorsModerationRouteImport.update({
  id: '/app/professors/moderation',
  path: '/app/professors/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfessorsProfessorIdRoute =
  AppProfessorsProfessorIdRouteImport.update({
    id: '/app/professors/$professorId',
    path: '/app/professors/$professorId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app/settings': typeof AppSettingsLayoutRoute
  '/app': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/verify-email/': typeof VerifyEmailIndexRoute
  '/app/professors/$professorId': typeof AppProfessorsProfessorIdRoute
  '/app/professors/moderation': typeof AppProfessorsModerationRoute
  '/app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/curriculum/': typeof AppCurriculumIndexRoute
  '/app/professors/': typeof AppProfessorsIndexRoute
  '/app/schedule/': typeof AppScheduleIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app': typeof AppIndexRoute
  '/login': typeof LoginIndexRoute
  '/signup': typeof SignupIndexRoute
  '/verify-email': typeof VerifyEmailIndexRoute
  '/app/professors/$professorId': typeof AppProfessorsProfessorIdRoute
  '/app/professors/moderation': typeof AppProfessorsModerationRoute
  '/app/settings': typeof AppSettingsIndexRoute
  '/app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/curriculum': typeof AppCurriculumIndexRoute
  '/app/professors': typeof AppProfessorsIndexRoute
  '/app/schedule': typeof AppScheduleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_index': typeof IndexRoute
  '/app/settings': typeof AppSettingsRouteRouteWithChildren
  '/app/_index': typeof AppIndexRoute
  '/login/': typeof LoginIndexRoute
  '/signup/': typeof SignupIndexRoute
  '/verify-email/': typeof VerifyEmailIndexRoute
  '/app/professors/$professorId': typeof AppProfessorsProfessorIdRoute
  '/app/professors/moderation': typeof AppProfessorsModerationRoute
  '/app/settings/_layout': typeof AppSettingsLayoutRoute
  '/app/settings/appearance': typeof AppSettingsAppearanceRoute
  '/app/settings/profile': typeof AppSettingsProfileRoute
  '/app/settings/security': typeof AppSettingsSecurityRoute
  '/app/curriculum/': typeof AppCurriculumIndexRoute
  '/app/professors/': typeof AppProfessorsIndexRoute
  '/app/schedule/': typeof AppScheduleIndexRoute
  '/app/settings/': typeof AppSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app/settings'
    | '/app'
    | '/login/'
    | '/signup/'
    | '/verify-email/'
    | '/app/professors/$professorId'
    | '/app/professors/moderation'
    | '/app/settings/appearance'
    | '/app/settings/profile'
    | '/app/settings/security'
    | '/app/curriculum/'
    | '/app/professors/'
    | '/app/schedule/'
    | '/app/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/app'
    | '/login'
    | '/signup'
    | '/verify-email'
    | '/app/professors/$professorId'
    | '/app/professors/moderation'
    | '/app/settings'
    | '/app/settings/appearance'
    | '/app/settings/profile'
    | '/app/settings/security'
    | '/app/curriculum'
    | '/app/professors'
    | '/app/schedule'
  id:
    | '__root__'
    | '/_index'
    | '/app/settings'
    | '/app/_index'
    | '/login/'
    | '/signup/'
    | '/verify-email/'
    | '/app/professors/$professorId'
    | '/app/professors/moderation'
    | '/app/settings/_layout'
    | '/app/settings/appearance'
    | '/app/settings/profile'
    | '/app/settings/security'
    | '/app/curriculum/'
    | '/app/professors/'
    | '/app/schedule/'
    | '/app/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppSettingsRouteRoute: typeof AppSettingsRouteRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  LoginIndexRoute: typeof LoginIndexRoute
  SignupIndexRoute: typeof SignupIndexRoute
  VerifyEmailIndexRoute: typeof VerifyEmailIndexRoute
  AppProfessorsProfessorIdRoute: typeof AppProfessorsProfessorIdRoute
  AppProfessorsModerationRoute: typeof AppProfessorsModerationRoute
  AppCurriculumIndexRoute: typeof AppCurriculumIndexRoute
  AppProfessorsIndexRoute: typeof AppProfessorsIndexRoute
  AppScheduleIndexRoute: typeof AppScheduleIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_index': {
      id: '/_index'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email/': {
      id: '/verify-email/'
      path: '/verify-email'
      fullPath: '/verify-email/'
      preLoaderRoute: typeof VerifyEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup/'
      preLoaderRoute: typeof SignupIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/_index': {
      id: '/app/_index'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/app/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/': {
      id: '/app/settings/'
      path: '/'
      fullPath: '/app/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/schedule/': {
      id: '/app/schedule/'
      path: '/app/schedule'
      fullPath: '/app/schedule/'
      preLoaderRoute: typeof AppScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/professors/': {
      id: '/app/professors/'
      path: '/app/professors'
      fullPath: '/app/professors/'
      preLoaderRoute: typeof AppProfessorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/curriculum/': {
      id: '/app/curriculum/'
      path: '/app/curriculum'
      fullPath: '/app/curriculum/'
      preLoaderRoute: typeof AppCurriculumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/settings/security': {
      id: '/app/settings/security'
      path: '/security'
      fullPath: '/app/settings/security'
      preLoaderRoute: typeof AppSettingsSecurityRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/profile': {
      id: '/app/settings/profile'
      path: '/profile'
      fullPath: '/app/settings/profile'
      preLoaderRoute: typeof AppSettingsProfileRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/appearance': {
      id: '/app/settings/appearance'
      path: '/appearance'
      fullPath: '/app/settings/appearance'
      preLoaderRoute: typeof AppSettingsAppearanceRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/settings/_layout': {
      id: '/app/settings/_layout'
      path: ''
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsLayoutRouteImport
      parentRoute: typeof AppSettingsRouteRoute
    }
    '/app/professors/moderation': {
      id: '/app/professors/moderation'
      path: '/app/professors/moderation'
      fullPath: '/app/professors/moderation'
      preLoaderRoute: typeof AppProfessorsModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/professors/$professorId': {
      id: '/app/professors/$professorId'
      path: '/app/professors/$professorId'
      fullPath: '/app/professors/$professorId'
      preLoaderRoute: typeof AppProfessorsProfessorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppSettingsRouteRouteChildren {
  AppSettingsLayoutRoute: typeof AppSettingsLayoutRoute
  AppSettingsAppearanceRoute: typeof AppSettingsAppearanceRoute
  AppSettingsProfileRoute: typeof AppSettingsProfileRoute
  AppSettingsSecurityRoute: typeof AppSettingsSecurityRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
}

const AppSettingsRouteRouteChildren: AppSettingsRouteRouteChildren = {
  AppSettingsLayoutRoute: AppSettingsLayoutRoute,
  AppSettingsAppearanceRoute: AppSettingsAppearanceRoute,
  AppSettingsProfileRoute: AppSettingsProfileRoute,
  AppSettingsSecurityRoute: AppSettingsSecurityRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
}

const AppSettingsRouteRouteWithChildren =
  AppSettingsRouteRoute._addFileChildren(AppSettingsRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppSettingsRouteRoute: AppSettingsRouteRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  LoginIndexRoute: LoginIndexRoute,
  SignupIndexRoute: SignupIndexRoute,
  VerifyEmailIndexRoute: VerifyEmailIndexRoute,
  AppProfessorsProfessorIdRoute: AppProfessorsProfessorIdRoute,
  AppProfessorsModerationRoute: AppProfessorsModerationRoute,
  AppCurriculumIndexRoute: AppCurriculumIndexRoute,
  AppProfessorsIndexRoute: AppProfessorsIndexRoute,
  AppScheduleIndexRoute: AppScheduleIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
