/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ModerationRouteImport } from './routes/moderation'
import { Route as IndexRouteImport } from './routes/_index'
import { Route as SettingsRouteRouteImport } from './routes/settings/route'
import { Route as AuthRouteRouteImport } from './routes/auth/route'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as ScheduleIndexRouteImport } from './routes/schedule/index'
import { Route as ProfessorsIndexRouteImport } from './routes/professors/index'
import { Route as PoliciesIndexRouteImport } from './routes/policies/index'
import { Route as OverviewIndexRouteImport } from './routes/overview/index'
import { Route as OnboardingIndexRouteImport } from './routes/onboarding/index'
import { Route as CurriculumIndexRouteImport } from './routes/curriculum/index'
import { Route as SettingsSecurityRouteImport } from './routes/settings/security'
import { Route as SettingsProfileRouteImport } from './routes/settings/profile'
import { Route as SettingsAppearanceRouteImport } from './routes/settings/appearance'
import { Route as ProfessorsProfessorIdRouteImport } from './routes/professors/$professorId'
import { Route as CurriculumCourseIdRouteImport } from './routes/curriculum/$courseId'
import { Route as AuthVerifyEmailIndexRouteImport } from './routes/auth/verify-email/index'
import { Route as AuthSignupIndexRouteImport } from './routes/auth/signup/index'
import { Route as AuthSigninIndexRouteImport } from './routes/auth/signin/index'
import { Route as AuthResetPasswordIndexRouteImport } from './routes/auth/reset-password/index'
import { Route as AuthMagicLinkIndexRouteImport } from './routes/auth/magic-link/index'
import { Route as Auth2faIndexRouteImport } from './routes/auth/2fa/index'
import { Route as EvaluationsViewEvaluationSlugRouteImport } from './routes/evaluations/view/$evaluationSlug'

const ModerationRoute = ModerationRouteImport.update({
  id: '/moderation',
  path: '/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/_index',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRouteRoute = SettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorsIndexRoute = ProfessorsIndexRouteImport.update({
  id: '/professors/',
  path: '/professors/',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesIndexRoute = PoliciesIndexRouteImport.update({
  id: '/policies/',
  path: '/policies/',
  getParentRoute: () => rootRouteImport,
} as any)
const OverviewIndexRoute = OverviewIndexRouteImport.update({
  id: '/overview/',
  path: '/overview/',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingIndexRoute = OnboardingIndexRouteImport.update({
  id: '/onboarding/',
  path: '/onboarding/',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumIndexRoute = CurriculumIndexRouteImport.update({
  id: '/curriculum/',
  path: '/curriculum/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsSecurityRoute = SettingsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsProfileRoute = SettingsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const SettingsAppearanceRoute = SettingsAppearanceRouteImport.update({
  id: '/appearance',
  path: '/appearance',
  getParentRoute: () => SettingsRouteRoute,
} as any)
const ProfessorsProfessorIdRoute = ProfessorsProfessorIdRouteImport.update({
  id: '/professors/$professorId',
  path: '/professors/$professorId',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumCourseIdRoute = CurriculumCourseIdRouteImport.update({
  id: '/curriculum/$courseId',
  path: '/curriculum/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifyEmailIndexRoute = AuthVerifyEmailIndexRouteImport.update({
  id: '/verify-email/',
  path: '/verify-email/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSignupIndexRoute = AuthSignupIndexRouteImport.update({
  id: '/signup/',
  path: '/signup/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthSigninIndexRoute = AuthSigninIndexRouteImport.update({
  id: '/signin/',
  path: '/signin/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthResetPasswordIndexRoute = AuthResetPasswordIndexRouteImport.update({
  id: '/reset-password/',
  path: '/reset-password/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AuthMagicLinkIndexRoute = AuthMagicLinkIndexRouteImport.update({
  id: '/magic-link/',
  path: '/magic-link/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const Auth2faIndexRoute = Auth2faIndexRouteImport.update({
  id: '/2fa/',
  path: '/2fa/',
  getParentRoute: () => AuthRouteRoute,
} as any)
const EvaluationsViewEvaluationSlugRoute =
  EvaluationsViewEvaluationSlugRouteImport.update({
    id: '/evaluations/view/$evaluationSlug',
    path: '/evaluations/view/$evaluationSlug',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/auth': typeof AuthRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/': typeof IndexRoute
  '/moderation': typeof ModerationRoute
  '/curriculum/$courseId': typeof CurriculumCourseIdRoute
  '/professors/$professorId': typeof ProfessorsProfessorIdRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/curriculum/': typeof CurriculumIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/overview/': typeof OverviewIndexRoute
  '/policies/': typeof PoliciesIndexRoute
  '/professors/': typeof ProfessorsIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/evaluations/view/$evaluationSlug': typeof EvaluationsViewEvaluationSlugRoute
  '/auth/2fa/': typeof Auth2faIndexRoute
  '/auth/magic-link/': typeof AuthMagicLinkIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/verify-email/': typeof AuthVerifyEmailIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteRouteWithChildren
  '/': typeof IndexRoute
  '/moderation': typeof ModerationRoute
  '/curriculum/$courseId': typeof CurriculumCourseIdRoute
  '/professors/$professorId': typeof ProfessorsProfessorIdRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/curriculum': typeof CurriculumIndexRoute
  '/onboarding': typeof OnboardingIndexRoute
  '/overview': typeof OverviewIndexRoute
  '/policies': typeof PoliciesIndexRoute
  '/professors': typeof ProfessorsIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/evaluations/view/$evaluationSlug': typeof EvaluationsViewEvaluationSlugRoute
  '/auth/2fa': typeof Auth2faIndexRoute
  '/auth/magic-link': typeof AuthMagicLinkIndexRoute
  '/auth/reset-password': typeof AuthResetPasswordIndexRoute
  '/auth/signin': typeof AuthSigninIndexRoute
  '/auth/signup': typeof AuthSignupIndexRoute
  '/auth/verify-email': typeof AuthVerifyEmailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/auth': typeof AuthRouteRouteWithChildren
  '/settings': typeof SettingsRouteRouteWithChildren
  '/_index': typeof IndexRoute
  '/moderation': typeof ModerationRoute
  '/curriculum/$courseId': typeof CurriculumCourseIdRoute
  '/professors/$professorId': typeof ProfessorsProfessorIdRoute
  '/settings/appearance': typeof SettingsAppearanceRoute
  '/settings/profile': typeof SettingsProfileRoute
  '/settings/security': typeof SettingsSecurityRoute
  '/curriculum/': typeof CurriculumIndexRoute
  '/onboarding/': typeof OnboardingIndexRoute
  '/overview/': typeof OverviewIndexRoute
  '/policies/': typeof PoliciesIndexRoute
  '/professors/': typeof ProfessorsIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/evaluations/view/$evaluationSlug': typeof EvaluationsViewEvaluationSlugRoute
  '/auth/2fa/': typeof Auth2faIndexRoute
  '/auth/magic-link/': typeof AuthMagicLinkIndexRoute
  '/auth/reset-password/': typeof AuthResetPasswordIndexRoute
  '/auth/signin/': typeof AuthSigninIndexRoute
  '/auth/signup/': typeof AuthSignupIndexRoute
  '/auth/verify-email/': typeof AuthVerifyEmailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/auth'
    | '/settings'
    | '/'
    | '/moderation'
    | '/curriculum/$courseId'
    | '/professors/$professorId'
    | '/settings/appearance'
    | '/settings/profile'
    | '/settings/security'
    | '/curriculum/'
    | '/onboarding/'
    | '/overview/'
    | '/policies/'
    | '/professors/'
    | '/schedule/'
    | '/settings/'
    | '/evaluations/view/$evaluationSlug'
    | '/auth/2fa/'
    | '/auth/magic-link/'
    | '/auth/reset-password/'
    | '/auth/signin/'
    | '/auth/signup/'
    | '/auth/verify-email/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/'
    | '/moderation'
    | '/curriculum/$courseId'
    | '/professors/$professorId'
    | '/settings/appearance'
    | '/settings/profile'
    | '/settings/security'
    | '/curriculum'
    | '/onboarding'
    | '/overview'
    | '/policies'
    | '/professors'
    | '/schedule'
    | '/settings'
    | '/evaluations/view/$evaluationSlug'
    | '/auth/2fa'
    | '/auth/magic-link'
    | '/auth/reset-password'
    | '/auth/signin'
    | '/auth/signup'
    | '/auth/verify-email'
  id:
    | '__root__'
    | '/auth'
    | '/settings'
    | '/_index'
    | '/moderation'
    | '/curriculum/$courseId'
    | '/professors/$professorId'
    | '/settings/appearance'
    | '/settings/profile'
    | '/settings/security'
    | '/curriculum/'
    | '/onboarding/'
    | '/overview/'
    | '/policies/'
    | '/professors/'
    | '/schedule/'
    | '/settings/'
    | '/evaluations/view/$evaluationSlug'
    | '/auth/2fa/'
    | '/auth/magic-link/'
    | '/auth/reset-password/'
    | '/auth/signin/'
    | '/auth/signup/'
    | '/auth/verify-email/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  SettingsRouteRoute: typeof SettingsRouteRouteWithChildren
  IndexRoute: typeof IndexRoute
  ModerationRoute: typeof ModerationRoute
  CurriculumCourseIdRoute: typeof CurriculumCourseIdRoute
  ProfessorsProfessorIdRoute: typeof ProfessorsProfessorIdRoute
  CurriculumIndexRoute: typeof CurriculumIndexRoute
  OnboardingIndexRoute: typeof OnboardingIndexRoute
  OverviewIndexRoute: typeof OverviewIndexRoute
  PoliciesIndexRoute: typeof PoliciesIndexRoute
  ProfessorsIndexRoute: typeof ProfessorsIndexRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  EvaluationsViewEvaluationSlugRoute: typeof EvaluationsViewEvaluationSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/moderation': {
      id: '/moderation'
      path: '/moderation'
      fullPath: '/moderation'
      preLoaderRoute: typeof ModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_index': {
      id: '/_index'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/schedule'
      fullPath: '/schedule/'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professors/': {
      id: '/professors/'
      path: '/professors'
      fullPath: '/professors/'
      preLoaderRoute: typeof ProfessorsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies/': {
      id: '/policies/'
      path: '/policies'
      fullPath: '/policies/'
      preLoaderRoute: typeof PoliciesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/overview/': {
      id: '/overview/'
      path: '/overview'
      fullPath: '/overview/'
      preLoaderRoute: typeof OverviewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding/': {
      id: '/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof OnboardingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/': {
      id: '/curriculum/'
      path: '/curriculum'
      fullPath: '/curriculum/'
      preLoaderRoute: typeof CurriculumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/security': {
      id: '/settings/security'
      path: '/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof SettingsSecurityRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/profile': {
      id: '/settings/profile'
      path: '/profile'
      fullPath: '/settings/profile'
      preLoaderRoute: typeof SettingsProfileRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/settings/appearance': {
      id: '/settings/appearance'
      path: '/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof SettingsAppearanceRouteImport
      parentRoute: typeof SettingsRouteRoute
    }
    '/professors/$professorId': {
      id: '/professors/$professorId'
      path: '/professors/$professorId'
      fullPath: '/professors/$professorId'
      preLoaderRoute: typeof ProfessorsProfessorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum/$courseId': {
      id: '/curriculum/$courseId'
      path: '/curriculum/$courseId'
      fullPath: '/curriculum/$courseId'
      preLoaderRoute: typeof CurriculumCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify-email/': {
      id: '/auth/verify-email/'
      path: '/verify-email'
      fullPath: '/auth/verify-email/'
      preLoaderRoute: typeof AuthVerifyEmailIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signup/': {
      id: '/auth/signup/'
      path: '/signup'
      fullPath: '/auth/signup/'
      preLoaderRoute: typeof AuthSignupIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/signin/': {
      id: '/auth/signin/'
      path: '/signin'
      fullPath: '/auth/signin/'
      preLoaderRoute: typeof AuthSigninIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/reset-password/': {
      id: '/auth/reset-password/'
      path: '/reset-password'
      fullPath: '/auth/reset-password/'
      preLoaderRoute: typeof AuthResetPasswordIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/magic-link/': {
      id: '/auth/magic-link/'
      path: '/magic-link'
      fullPath: '/auth/magic-link/'
      preLoaderRoute: typeof AuthMagicLinkIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/auth/2fa/': {
      id: '/auth/2fa/'
      path: '/2fa'
      fullPath: '/auth/2fa/'
      preLoaderRoute: typeof Auth2faIndexRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/evaluations/view/$evaluationSlug': {
      id: '/evaluations/view/$evaluationSlug'
      path: '/evaluations/view/$evaluationSlug'
      fullPath: '/evaluations/view/$evaluationSlug'
      preLoaderRoute: typeof EvaluationsViewEvaluationSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteRouteChildren {
  Auth2faIndexRoute: typeof Auth2faIndexRoute
  AuthMagicLinkIndexRoute: typeof AuthMagicLinkIndexRoute
  AuthResetPasswordIndexRoute: typeof AuthResetPasswordIndexRoute
  AuthSigninIndexRoute: typeof AuthSigninIndexRoute
  AuthSignupIndexRoute: typeof AuthSignupIndexRoute
  AuthVerifyEmailIndexRoute: typeof AuthVerifyEmailIndexRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  Auth2faIndexRoute: Auth2faIndexRoute,
  AuthMagicLinkIndexRoute: AuthMagicLinkIndexRoute,
  AuthResetPasswordIndexRoute: AuthResetPasswordIndexRoute,
  AuthSigninIndexRoute: AuthSigninIndexRoute,
  AuthSignupIndexRoute: AuthSignupIndexRoute,
  AuthVerifyEmailIndexRoute: AuthVerifyEmailIndexRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface SettingsRouteRouteChildren {
  SettingsAppearanceRoute: typeof SettingsAppearanceRoute
  SettingsProfileRoute: typeof SettingsProfileRoute
  SettingsSecurityRoute: typeof SettingsSecurityRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
}

const SettingsRouteRouteChildren: SettingsRouteRouteChildren = {
  SettingsAppearanceRoute: SettingsAppearanceRoute,
  SettingsProfileRoute: SettingsProfileRoute,
  SettingsSecurityRoute: SettingsSecurityRoute,
  SettingsIndexRoute: SettingsIndexRoute,
}

const SettingsRouteRouteWithChildren = SettingsRouteRoute._addFileChildren(
  SettingsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthRouteRoute: AuthRouteRouteWithChildren,
  SettingsRouteRoute: SettingsRouteRouteWithChildren,
  IndexRoute: IndexRoute,
  ModerationRoute: ModerationRoute,
  CurriculumCourseIdRoute: CurriculumCourseIdRoute,
  ProfessorsProfessorIdRoute: ProfessorsProfessorIdRoute,
  CurriculumIndexRoute: CurriculumIndexRoute,
  OnboardingIndexRoute: OnboardingIndexRoute,
  OverviewIndexRoute: OverviewIndexRoute,
  PoliciesIndexRoute: PoliciesIndexRoute,
  ProfessorsIndexRoute: ProfessorsIndexRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  EvaluationsViewEvaluationSlugRoute: EvaluationsViewEvaluationSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
