-- 0050_add_sync_seed_run_ledger.sql
-- Tracks tec-data delta seed generation/application lifecycle.

BEGIN;

CREATE TABLE IF NOT EXISTS public.sync_seed_run (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seed_file_name TEXT NOT NULL,
  seed_sha256 TEXT NOT NULL,
  scope TEXT NOT NULL CHECK (scope IN ('catalog', 'offering', 'mixed')),
  years INTEGER[] NOT NULL DEFAULT '{}'::INTEGER[],
  term_external_keys TEXT[] NOT NULL DEFAULT '{}'::TEXT[],
  generated_at_utc TIMESTAMPTZ NOT NULL,
  applied_at_utc TIMESTAMPTZ,
  status TEXT NOT NULL CHECK (status IN ('generated', 'applied', 'failed', 'skipped_duplicate')),
  error_message TEXT,
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE UNIQUE INDEX IF NOT EXISTS uq_sync_seed_run_seed_sha256
  ON public.sync_seed_run(seed_sha256);

CREATE INDEX IF NOT EXISTS idx_sync_seed_run_status
  ON public.sync_seed_run(status);

CREATE INDEX IF NOT EXISTS idx_sync_seed_run_generated_at_utc
  ON public.sync_seed_run(generated_at_utc DESC);

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_trigger
    WHERE tgname = 'set_timestamp_sync_seed_run'
  ) THEN
    CREATE TRIGGER set_timestamp_sync_seed_run
      BEFORE UPDATE ON public.sync_seed_run
      FOR EACH ROW
      EXECUTE FUNCTION public.trigger_set_timestamp();
  END IF;
END $$;

COMMIT;
