-- 0068_prepare_better_auth_schema.sql
-- Prepare an isolated schema for Better Auth tables.
-- The Better Auth CLI must create the actual auth tables in this schema.

BEGIN;

CREATE SCHEMA IF NOT EXISTS better_auth;

-- Keep Better Auth tables outside the exposed public schema. Direct access is via
-- the Worker/database connection, not Supabase Data API.
REVOKE ALL ON SCHEMA better_auth FROM anon, authenticated;

COMMENT ON SCHEMA better_auth IS 'Better Auth managed schema. Tables are generated by the Better Auth CLI.';

COMMIT;
