BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type
    WHERE typname = 'professor_review_report_status'
      AND typnamespace = 'public'::regnamespace
  ) THEN
    CREATE TYPE public.professor_review_report_status AS ENUM ('pending', 'resolved', 'dismissed');
  END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS public.professor_review_report (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id BIGINT NOT NULL REFERENCES public.professor_review(id) ON DELETE CASCADE,
  reason TEXT NOT NULL CHECK (reason IN ('spam', 'ofensivo', 'acoso', 'datos_personales', 'falso_enganoso', 'otro')),
  description TEXT,
  status public.professor_review_report_status NOT NULL DEFAULT 'pending',
  resolution_note TEXT,
  resolved_by UUID REFERENCES public.user(id),
  resolved_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT professor_review_report_description_required_for_otro CHECK (
    reason <> 'otro' OR NULLIF(BTRIM(COALESCE(description, '')), '') IS NOT NULL
  )
);

CREATE INDEX IF NOT EXISTS idx_professor_review_report_pending_created_at
  ON public.professor_review_report (created_at DESC)
  WHERE status = 'pending';

CREATE INDEX IF NOT EXISTS idx_professor_review_report_review_id
  ON public.professor_review_report (review_id);

ALTER TABLE public.professor_review_report ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Admins can read professor review reports" ON public.professor_review_report;
CREATE POLICY "Admins can read professor review reports"
  ON public.professor_review_report
  FOR SELECT
  TO authenticated
  USING (public.is_admin());

DROP POLICY IF EXISTS "Admins can update professor review reports" ON public.professor_review_report;
CREATE POLICY "Admins can update professor review reports"
  ON public.professor_review_report
  FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS "Service role can insert professor review reports" ON public.professor_review_report;
CREATE POLICY "Service role can insert professor review reports"
  ON public.professor_review_report
  FOR INSERT
  TO service_role
  WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.touch_professor_review_report_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_touch_professor_review_report_updated_at ON public.professor_review_report;
CREATE TRIGGER trg_touch_professor_review_report_updated_at
BEFORE UPDATE ON public.professor_review_report
FOR EACH ROW
EXECUTE FUNCTION public.touch_professor_review_report_updated_at();

CREATE OR REPLACE FUNCTION public.get_professor_review_reports_for_moderation(
  p_status public.professor_review_report_status DEFAULT 'pending',
  p_limit INTEGER DEFAULT 20,
  p_offset INTEGER DEFAULT 0
)
RETURNS TABLE (
  report_id BIGINT,
  review_id BIGINT,
  reason TEXT,
  description TEXT,
  status public.professor_review_report_status,
  created_at TIMESTAMPTZ,
  professor_id BIGINT,
  professor_name TEXT,
  course_code TEXT,
  course_name TEXT,
  comment TEXT,
  total_count BIGINT
)
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;

  RETURN QUERY
  WITH filtered AS (
    SELECT r.*
    FROM public.professor_review_report r
    WHERE r.status = p_status
  ),
  total AS (
    SELECT COUNT(*)::BIGINT AS count
    FROM filtered
  )
  SELECT
    r.id AS report_id,
    pr.id AS review_id,
    r.reason,
    r.description,
    r.status,
    r.created_at,
    p.id AS professor_id,
    p.full_name AS professor_name,
    pr.course_code_snapshot AS course_code,
    COALESCE(NULLIF(BTRIM(pr.course_name_snapshot), ''), c.name) AS course_name,
    pr.comment,
    t.count AS total_count
  FROM filtered r
  JOIN public.professor_review pr ON pr.id = r.review_id
  JOIN public.professor p ON p.id = pr.professor_id
  JOIN public.course c ON c.id = pr.course_id
  CROSS JOIN total t
  ORDER BY r.created_at ASC, r.id ASC
  LIMIT GREATEST(p_limit, 0)
  OFFSET GREATEST(p_offset, 0);
END;
$$;

REVOKE ALL ON FUNCTION public.get_professor_review_reports_for_moderation(public.professor_review_report_status, INTEGER, INTEGER) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_professor_review_reports_for_moderation(public.professor_review_report_status, INTEGER, INTEGER) TO authenticated;

CREATE OR REPLACE FUNCTION public.moderate_professor_review_report(
  p_report_id BIGINT,
  p_new_status public.professor_review_report_status,
  p_resolution_note TEXT DEFAULT NULL
)
RETURNS public.professor_review_report
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public
AS $$
DECLARE
  updated_row public.professor_review_report;
BEGIN
  IF NOT public.is_admin() THEN
    RAISE EXCEPTION 'Not authorized';
  END IF;

  IF p_new_status NOT IN ('resolved', 'dismissed') THEN
    RAISE EXCEPTION 'Invalid moderation status: %', p_new_status;
  END IF;

  UPDATE public.professor_review_report r
  SET
    status = p_new_status,
    resolution_note = NULLIF(BTRIM(COALESCE(p_resolution_note, '')), ''),
    resolved_by = public.current_user_id(),
    resolved_at = NOW(),
    updated_at = NOW()
  WHERE r.id = p_report_id
  RETURNING r.* INTO updated_row;

  IF updated_row.id IS NULL THEN
    RAISE EXCEPTION 'Report not found: %', p_report_id;
  END IF;

  RETURN updated_row;
END;
$$;

REVOKE ALL ON FUNCTION public.moderate_professor_review_report(BIGINT, public.professor_review_report_status, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.moderate_professor_review_report(BIGINT, public.professor_review_report_status, TEXT) TO authenticated;

COMMIT;
