BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_type
    WHERE typname = 'feedback_type'
      AND typnamespace = 'public'::regnamespace
  ) THEN
    CREATE TYPE public.feedback_type AS ENUM ('bug', 'feature', 'other');
  END IF;
END;
$$;

CREATE TABLE IF NOT EXISTS public.user_feedback (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  type public.feedback_type NOT NULL DEFAULT 'other',
  content TEXT NOT NULL,
  is_reviewed BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_user_feedback_created_at ON public.user_feedback (created_at DESC);

ALTER TABLE public.user_feedback ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Anyone can create feedback" ON public.user_feedback;
CREATE POLICY "Anyone can create feedback"
  ON public.user_feedback
  FOR INSERT
  TO public
  WITH CHECK (true);

DROP POLICY IF EXISTS "Admins can read all feedback" ON public.user_feedback;
CREATE POLICY "Admins can read all feedback"
  ON public.user_feedback
  FOR SELECT
  TO authenticated
  USING (public.is_admin());

DROP POLICY IF EXISTS "Admins can update feedback" ON public.user_feedback;
CREATE POLICY "Admins can update feedback"
  ON public.user_feedback
  FOR UPDATE
  TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

COMMIT;
